### ISSUE TITLE
Annoying Package error

### ISSUE THREAD

**Issue by AndrewNovakP** [vertxxyz/Vertx.Debugging#10]
Hi. I have an annoying console error: Asset Packages/com.vertx.debugging/Editor/Assets has no meta file, but it's in an immutable folder. The asset will be ignored.

Unity 2021.3.15
com.vertx.debugging v2.0.4 OpenUPM

Please add .meta file for the Assets folder to fix it ;)

**Comment by vertxxyz** [comment]
This is a bug because there previously was a meta file. There should not be a folder at all, or a meta file. The bug is transient and only based on the state of the package cache.
You can delete any Assets folder that hasn't been cleaned up in the package (it should be empty).

**Comment by vertxxyz** [comment]
Actually, now I look at it further I was mistaking two issues; it's a discrepancy between how OpenUPM handles gitignores, and how git does. I have this meta file present in git, but OpenUPM does not publish it. I've changed some names in the gitignore and this seems to have fixed it (in version `2.0.6`)

**Comment by AndrewNovakP** [comment]
@vertxxyz I understand. Thanks for fix ^_^
