### ISSUE TITLE
DrawPhysics2D is Not available for 2021.3.17

### ISSUE THREAD

**Issue by AndrewNovakP** [vertxxyz/Vertx.Debugging#11]
Hi. 
DrawPhysics2D is Not available for Unity 2021.3.17 at all. Can you support this major version?

**Comment by vertxxyz** [comment]
Hi, thanks for the report, this seems to have been a mistaken define, unsure how it got there.
This has been fixed in `2.1.0` which is now on OpenUPM.

**Comment by AndrewNovakP** [comment]
Thanks
