### ISSUE TITLE
Add via git URL not working

### ISSUE THREAD

**Issue by artvel** [vertxxyz/Vertx.Debugging#14]
[Package Manager Window] Cannot perform upm operation: Unable to add package [https://github.com/vertxxyz/Vertx.Debugging]:
  Package name 'https://github.com/vertxxyz/Vertx.Debugging' is invalid. [InvalidParameter].
UnityEditor.EditorApplication:Internal_CallUpdateFunctions () (at /Users/bokken/build/output/unity/unity/Editor/Mono/EditorApplication.cs:356)

**Comment by vertxxyz** [comment]
`https://github.com/vertxxyz/Vertx.Debugging.git` is the git url.
I don't advise you add via git, but instead use the instructions listed and use OpenUPM.
