### ISSUE TITLE
Feature request: Draw path

### ISSUE THREAD

**Issue by rhys-vdw** [vertxxyz/Vertx.Debugging#2]
Would be nice to have variants of `DrawLine` and `DrawArrowLine` for drawing an `IEnumerable<Vector3>`/`Vector3[]`.

**Comment by vertxxyz** [comment]
Added in 1,9,0,
Just pushed it so it should propagate to OpenUPM in under an hour if all is well.

**Comment by rhys-vdw** [comment]
Absolute legend.
