### ISSUE TITLE
Support drawing PolygonCollider2D

### ISSUE THREAD

**Issue by rhys-vdw** [vertxxyz/Vertx.Debugging#22]
Currently this is not supported.

https://github.com/vertxxyz/Vertx.Debugging/blob/4986c28517ace563c06985334bf4b17429aa5997/Runtime/Draw.cs#L194-L241

**Comment by vertxxyz** [comment]
I'm in Copenhagen for a bit, so I might be a bit delayed in getting to these issues and PR. Hopefully you're fine running a fork for a bit in the meantime :)

**Comment by rhys-vdw** [comment]
No rush, I'm just putting stuff here as I go. :-)

Have a great time. 🎉

**Comment by vertxxyz** [comment]
Released 2.2.0.
