### ISSUE TITLE
can only works below [Projects Settings > Graphics > Render Graph>  Compatibility Mode]  in Unity6

### ISSUE THREAD

**Issue by franktmy** [vertxxyz/Vertx.Debugging#27]
And Unity said they no longer support Compatibility Mode：

The project currently uses the compatibility mode where the Render Graph API is disabled. Support for this mode will be removed in future Unity versions. Migrate existing ScriptableRenderPasses to the new RenderGraph API. After the migration, disable the compatibility mode in Edit > Projects Settings > Graphics > Render Graph.

By the way. Thanks for developing such wonderful tool.

**Comment by vertxxyz** [comment]
#25 handles this. [release/v3.0.0](https://github.com/vertxxyz/Vertx.Debugging/tree/release/v3.0.0) should work, but I have a number of large changes on there and not enough time to address it all
