### ISSUE TITLE
errata: it's https://github.com/vertxxyz/Vertx.Debugging.git, not  com.vertx.debugging

### ISSUE THREAD

**Issue by laurentopia** [vertxxyz/Vertx.Debugging#28]
in the UPM/+

**Comment by vertxxyz** [comment]
What are you talking about?

**Comment by laurentopia** [comment]
(this debugging lib is so good)

**Comment by laurentopia** [comment]
![image](https://github.com/vertxxyz/Vertx.Debugging/assets/26075468/a9cb88cb-f81f-4a77-af6c-ede464470f78)
this^

**Comment by laurentopia** [comment]
that's wrong 
![image](https://github.com/vertxxyz/Vertx.Debugging/assets/26075468/327c38f9-bb4c-4693-a6d5-776d9a5a6283)

**Comment by vertxxyz** [comment]
I don't recommend using the git as a way to reference the package, so I don't list it as a method.
What I list in the README is the recommended and correct way to add the package. You have to follow ALL the instructions in that box.

**Comment by laurentopia** [comment]
yep, and that doesn't work
![image](https://github.com/vertxxyz/Vertx.Debugging/assets/26075468/392840f9-cd23-4f05-9b12-a37e2501c702)
![image](https://github.com/vertxxyz/Vertx.Debugging/assets/26075468/5f8bdef0-405a-4442-888d-2e8459543011)

**Comment by vertxxyz** [comment]
And did you add the OpenUPM scope?

**Comment by laurentopia** [comment]
ah they're meant to be done together? the page layout led me think that they were either/or since it's usually how UPM stuff is in other packages, including unity's. 
i'll change that. cheers
