### ISSUE TITLE
shapes available

### ISSUE THREAD

**Issue by laurentopia** [vertxxyz/Vertx.Debugging#29]
I see a circle, is there a way to fill it to make it a disc?
Also is there a way to draw a multiline by feeding it a Vector3[]?

**Comment by vertxxyz** [comment]
I don't support solid shapes: https://github.com/vertxxyz/Vertx.Debugging/issues/15

And `Shape.LineStrip` takes an Enumerable of Vector3 which is draws a connected line between the input points.
