### ISSUE TITLE
documentation 404

### ISSUE THREAD

**Issue by laurentopia** [vertxxyz/Vertx.Debugging#30]
![image](https://github.com/vertxxyz/Vertx.Debugging/assets/26075468/0e6a8ad7-f211-46e5-bc3e-02a267c90995)
https://github.com/Packages/com.vertx.debugging@2.3/api/Vertx.Debugging.Shape.Arc.html
![image](https://github.com/vertxxyz/Vertx.Debugging/assets/26075468/9b2279e2-4179-4b01-82e7-68610c763e7b)

**Comment by vertxxyz** [comment]
Your IDE has generated this link, it's not a part of this package.
I don't have summary comments on all members, which is certainly something I could look to improve, but I don't currently have the time to do that.

**Comment by laurentopia** [comment]
I see, if you have the docs split per URL, I can start adding that as I use your lib.

**Comment by vertxxyz** [comment]
I am not sure what you mean. I don't host any documentation apart from what little is in the README and summary comments in the code.

**Comment by laurentopia** [comment]
that's what i meant. zero url doc, i'll turn off rider auto doc then
