### ISSUE TITLE
Request: Spherecast with same signature as Physics.SphereCast

### ISSUE THREAD

**Issue by laurentopia** [vertxxyz/Vertx.Debugging#31]
I started replacing Unity's physics stuff with your stuff because having debug is more convenient, plus it seems that your stuff removes all extra display on build.

**Comment by vertxxyz** [comment]
What overload is missing from `DrawPhysics.SphereCast`?

**Comment by laurentopia** [comment]
DrawPhysics.SphereCast doesn't have layermask or query trigger like this does. https://docs.unity3d.com/ScriptReference/Physics.SphereCast.html

**Comment by vertxxyz** [comment]
Can you be specific about which overload you're talking about? Because there are overloads with layer mask and trigger queries https://github.com/vertxxyz/Vertx.Debugging/blob/master/Runtime%2FDrawPhysics.cs#L254

**Comment by laurentopia** [comment]
Well that's strange, now I can see it.
