### ISSUE TITLE
request: DrawPhysics implements all phycs

### ISSUE THREAD

**Issue by laurentopia** [vertxxyz/Vertx.Debugging#32]
so we can get stuff like this in Editor mode debug:
![image](https://github.com/user-attachments/assets/fed09f6e-27e6-4622-a575-9227374205e1)
![image](https://github.com/user-attachments/assets/67638fff-64b1-4451-8f7c-a651cad68ef8)
yeah i'm doing that
![image](https://github.com/user-attachments/assets/4f523c54-cb1c-49ef-906d-58276be8d828)

**Comment by vertxxyz** [comment]
Sorry, This isn't feasible to maintain or within the scope of the debugging API. You'll just have to specify the full `UnityEngine.Physics` in those few cases where there's mixed usages in one file.
