### ISSUE TITLE
how do you make an anulus that's +50, -20 degree around the direction?

### ISSUE THREAD

**Issue by laurentopia** [vertxxyz/Vertx.Debugging#35]
Angle only produces a symmetrical pie and I'd like to represent a joint with a + and minus angle where + != minus degree
![image](https://github.com/user-attachments/assets/5b3847b4-8064-4986-9ad4-d689a4807bd0)

**Comment by vertxxyz** [comment]
I've just added some overloads of Arc and Annulus to the 3.0.0 branch (not on UPM, tbd when I release it)

You can see how I've done it here:
https://github.com/vertxxyz/Vertx.Debugging/commit/4c2dcddc603803f8a45f22cfac4d7405e584a16e#diff-5727d04b66b54b516ed110abb20ff49bf9ec74db4a1b2535d655231f801ebce4R948

With a call from the new overloads looking like this:
https://github.com/vertxxyz/Vertx.Debugging/commit/4c2dcddc603803f8a45f22cfac4d7405e584a16e#diff-5727d04b66b54b516ed110abb20ff49bf9ec74db4a1b2535d655231f801ebce4R1020

If you're not using that branch and want to stay on UPM you can adjust the rotation and angle in a similar way.

**Comment by laurentopia** [comment]
Thanks, I'll wait for release.
