### ISSUE TITLE
Text camera expression is flipped?

### ISSUE THREAD

**Issue by DoomT-AliW** [vertxxyz/Vertx.Debugging#37]
Reading the docs it says if the Camera parameter is not defined in Text constructor, then the scene camera is used.

But looking at the code it was:
```
Camera camera = SceneView.currentDrawingSceneView?.camera ?? textData.Camera;
```

I had to change it to:

```
Camera camera = textData.Camera ?? SceneView.currentDrawingSceneView?.camera;
```

for it to take the game's main camera in the game view.

**Comment by vertxxyz** [comment]
It's not flipped, but the code does seem poorly-written. I've re-written the code for clarity and merged the version 3.0.0 branch; if you weren't using it already it might fix the text drawing issue.
> **camera:** If a camera is not provided, the text will *only* draw in the Scene view.

**Comment by DoomT-AliW** [comment]
Thanks for the rapid reply.

I've just started using the library at work yesterday, I've made quite a few other changes. Do you have a release log for 3.0.0? does it contain a lot more fixes or just that text rework?

Thanks

**Comment by DoomT-AliW** [comment]
In the update, I still had to do this change so text renders in the game view:

in Draw.Text.cs, line 111

```
if (uses3DIcons)

```

I changed to: 

```
if (uses3DIcons && isSceneView)
```

Otherwise nothing shows up in game view camera, probably since my game is top-down and the camera is probably further away than that fade distance. I'm not sure if there's a better way
