### ISSUE TITLE
is there a way to draw a colored point or a shaded sphere? 

### ISSUE THREAD

**Issue by laurentopia** [vertxxyz/Vertx.Debugging#42]
I only see wireframes and was wondering if there was a way to show a color at a point in space.

**Comment by dragon122** [comment]
D.raw(new Shape.Point(<Position>), <Color>);

**Comment by vertxxyz** [comment]
There are no solid shapes.
https://github.com/vertxxyz/Vertx.Debugging/issues/38
https://github.com/vertxxyz/Vertx.Debugging/issues/15
